### ISSUE TITLE
dellos6_config failing

### ISSUE THREAD

**Issue by ryanmerolle** [Dell-Networking/ansible-dellos-examples#12]
dellos6_config fails with minimal output.  I increased the timers just in case, and verified that I could ssh to the host via the command ansible host.
```
2019-01-21 20:00:54,885 p=4908 u=rmerolle |  network_os is set to dellos6
2019-01-21 20:00:54,988 p=4915 u=rmerolle | paramiko [172.16.13.11] starting thread (client mode): 0x3270210L
2019-01-21 20:00:54,989 p=4915 u=rmerolle | paramiko [172.16.13.11] Local version/idstring: SSH-2.0-paramiko_2.4.2
2019-01-21 20:00:55,029 p=4915 u=rmerolle | paramiko [172.16.13.11] Remote version/idstring: SSH-2.0-OpenSSH_7.5
2019-01-21 20:00:55,029 p=4915 u=rmerolle | paramiko [172.16.13.11] Connected (version 2.0, client OpenSSH_7.5)
2019-01-21 20:00:55,065 p=4915 u=rmerolle | paramiko [172.16.13.11] kex algos:[u'curve25519-sha256', u'curve25519-sha256@libssh.org', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group16-sha512', u'diffie-hellman-group18-sha512', u'diffie-hellman-group14-sha256', u'diffie-hellman-group14-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256'] client encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'chacha20-poly1305@openssh.com', u''] server encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'chacha20-poly1305@openssh.com', u''] client mac:[u'hmac-sha1', u'hmac-sha1-etm@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u''] server mac:[u'hmac-sha1', u'hmac-sha1-etm@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u''] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2019-01-21 20:00:55,066 p=4915 u=rmerolle | paramiko [172.16.13.11] Kex agreed: diffie-hellman-group-exchange-sha256
2019-01-21 20:00:55,066 p=4915 u=rmerolle | paramiko [172.16.13.11] HostKey agreed: ssh-rsa
2019-01-21 20:00:55,067 p=4915 u=rmerolle | paramiko [172.16.13.11] Cipher agreed: aes128-ctr
2019-01-21 20:00:55,067 p=4915 u=rmerolle | paramiko [172.16.13.11] MAC agreed: hmac-sha2-256
2019-01-21 20:00:55,068 p=4915 u=rmerolle | paramiko [172.16.13.11] Compression agreed: none
2019-01-21 20:00:55,764 p=4915 u=rmerolle | paramiko [172.16.13.11] Got server p (8192 bits)
2019-01-21 20:00:58,819 p=4915 u=rmerolle | paramiko [172.16.13.11] kex engine KexGexSHA256 specified hash_algo <built-in function openssl_sha256>
2019-01-21 20:00:58,821 p=4915 u=rmerolle | paramiko [172.16.13.11] Switch to new keys ...
2019-01-21 20:00:58,925 p=4915 u=rmerolle | paramiko [172.16.13.11] userauth is OK
2019-01-21 20:01:03,040 p=4915 u=rmerolle | paramiko [172.16.13.11] Authentication (password) successful!
2019-01-21 20:01:03,064 p=4915 u=rmerolle | paramiko [172.16.13.11] [chan 0] Max packet in: 32768 bytes
2019-01-21 20:01:03,088 p=4915 u=rmerolle | paramiko [172.16.13.11] Received global request "hostkeys-00@openssh.com"
2019-01-21 20:01:03,089 p=4915 u=rmerolle | paramiko [172.16.13.11] Rejecting "hostkeys-00@openssh.com" global request from server.
2019-01-21 20:01:03,128 p=4915 u=rmerolle | paramiko [172.16.13.11] [chan 0] Max packet out: 32768 bytes
2019-01-21 20:01:03,128 p=4915 u=rmerolle | paramiko [172.16.13.11] Secsh channel 0 opened.
2019-01-21 20:01:03,178 p=4915 u=rmerolle | paramiko [172.16.13.11] [chan 0] Sesch channel 0 request ok
2019-01-21 20:01:03,218 p=4915 u=rmerolle | paramiko [172.16.13.11] [chan 0] Sesch channel 0 request ok
2019-01-21 20:01:04,171 p=4896 u=rmerolle |  Using module file /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible/modules/network/dellos6/dellos6_config.py
2019-01-21 20:01:44,314 p=4908 u=rmerolle |  command timeout triggered, timeout value is 40 secs.
See the timeout setting options in the Network Debug and Troubleshooting Guide.
2019-01-21 20:01:44,343 p=4896 u=rmerolle |  The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/var/folders/5l/b5g8v52d1cn_6d_zvccsjss4pdcnx3/T/ansible_dellos6_config_payload_lVlaGE/ansible_dellos6_config_payload.zip/ansible/module_utils/network/dellos6/dellos6.py", line 86, in get_config
    return _DEVICE_CONFIGS[cmd]

2019-01-21 20:01:44,344 p=4896 u=rmerolle |  fatal: [172.16.13.11]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "after": null, 
            "auth_pass": null, 
            "authorize": null, 
            "backup": true, 
            "before": null, 
            "config": null, 
            "host": null, 
            "lines": null, 
            "match": "line", 
            "parents": null, 
            "password": null, 
            "port": null, 
            "provider": null, 
            "replace": "line", 
            "save": false, 
            "src": null, 
            "ssh_keyfile": null, 
            "timeout": null, 
            "update": "merge", 
            "username": null
        }
    }, 
    "msg": "unable to retrieve current config", 
    "stderr": "command timeout triggered, timeout value is 40 secs.\nSee the timeout setting options in the Network Debug and Troubleshooting Guide.", 
    "stderr_lines": [
        "command timeout triggered, timeout value is 40 secs.", 
        "See the timeout setting options in the Network Debug and Troubleshooting Guide."
    ]
}
2019-01-21 20:01:44,345 p=4915 u=rmerolle | paramiko [172.16.13.11] [chan 0] EOF sent (0)
2019-01-21 20:01:44,385 p=4915 u=rmerolle | paramiko [172.16.13.11] EOF in transport thread
2019-01-21 20:01:44,416 p=4896 u=rmerolle |  PLAY RECAP ***************************************************************************************************************************************
2019-01-21 20:01:44,416 p=4896 u=rmerolle |  172.16.13.11               : ok=1    changed=0    unreachable=0    failed=1   
2019-01-21 20:01:44,416 p=4896 u=rmerolle |  localhost                  : ok=1    changed=0    unreachable=0    failed=0   
2019-01-21 20:01:44,517 p=4908 u=rmerolle |  shutdown complete
2019-01-21 20:02:05,490 p=5063 u=rmerolle |  ansible-playbook 2.7.6
  config file = /Users/rmerolle/repos/git/network-automation/ad-hoc/ansible.cfg
  configured module search path = [u'/Users/rmerolle/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible
  executable location = /Library/Frameworks/Python.framework/Versions/2.7/bin/ansible-playbook
  python version = 2.7.15 (v2.7.15:ca079a3ea3, Apr 29 2018, 20:59:26) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
```
associated vars:
```
ansible_network_os: dellos6
ansible_connection: network_cli
ansible_command_timeout: 180
ansible_buffer_read_timeout: 10
ansible_user: user
ansible_ssh_pass: password
```

associated task:
```
- name: PULL CONFIG
  dellos6_config:
    backup: yes
  register: config_output
```

**Comment by skg-net** [comment]
@ryanmerolle Thanks for reporting, we will look into the issue. Can you please let us know which platform are you using and what is the OS version being used?

**Comment by ryanmerolle** [comment]
Dell EMC Networking N3048P 6.5.2.17

**Comment by abirami-n** [comment]
@ryanmerolle we weren't able to reproduce the issue in spite of increasing the timeout, can you provide more information regarding the show running-config? Is it huge ? If you have a stack, etc;

**Comment by ryanmerolle** [comment]
512 lines of config.
No stacking.
We can setup a screen share and walk through it if you like.  I can also email you show commands via your dell email.

**Comment by ryanmerolle** [comment]
I have the same issue with a new N3048EP-ON running 6.5.3.33.

**Comment by abirami-n** [comment]
@ryanmerolle Can you share the output of show commands(running config, etc; ) via dell email , [abirami_n@dell.com]

**Comment by rolfhh** [comment]
I'm able to reliably reproduce this on an N1148P-ON running v6.6.0.2 firmware. Ansible is version 2.7.10 on Ubuntu 18.04.02.

The cause in my particular case is a flaw in the on_become() function in ansible/lib/ansible/plugins/terminal/dellos6.py. The function is written in such a way that if the switch is configured to go directly into enable mode after authenticating through SSH, on_become() fails to issue the "terminal length 0" command. This means that when Ansible issues the "show running-config" command it just gets stuck at the first page of the config and times out.

On a factory-default switch you can reproduce the problem by adding a local user and entering these two lines of configuration:
```
aaa authentication login default local
aaa authorization exec default local
```
The last line is the one that sends you directly to enable mode after logging in through SSH.

To fix the issue you can modify the if statement at the very beginning of on_become():
```
def on_become(self, passwd=None):
    if self._get_prompt().endswith('#'):
        return
```

Copy-paste the "terminal length 0" lines from the bottom of on_becom() into the if statement:
```
def on_become(self, passwd=None):
    if self._get_prompt().endswith('#'):
        try:
            self._exec_cli_command(b'terminal length 0')
        except AnsibleConnectionFailure:
            raise AnsibleConnectionFailure('unable to set terminal parameters')
        return
```

**Comment by ryanmerolle** [comment]
https://github.com/ansible/ansible/issues/55833

**Comment by jsteel44** [comment]
I wonder if I'm hitting this same issue on my N3048 switches running DellOS 6 and Ansible 2.7, my error is:

```
Traceback (most recent call last):
  File "/usr/bin/ansible-connection", line 106, in start
    self.connection._connect()
  File "/usr/lib/python3.7/site-packages/ansible/plugins/connection/network_cli.py", line 341, in _connect
    self._terminal.on_become(passwd=auth_pass)
  File "/usr/lib/python3.7/site-packages/ansible/plugins/terminal/dellos6.py", line 54, in on_become
    if self._get_prompt().endswith('#'):
TypeError: endswith first arg must be bytes or a tuple of bytes, not str
```

But @rolfhh I tried your fix but it doesn't seem to make any difference here. Is this related? Thanks.

**Comment by rolfhh** [comment]
@jsteel44 This looks like a separate bug. The error message is complaining about '#' being a string, while endswith() is expecting a bytes object or byte tuple. Not sure why I'm not getting the same error, although it looks like you're running Ansible under Python 3.7 whereas I'm running it under 2.7 (Ansible 2.5+ should work under Python 3 though).

Try changing:
````
if self._get_prompt().endswith('#'):
````
Into:
````
if self._get_prompt().endswith(b'#'):
````

The b prefix will turn the string literal into a bytes literal, which should fix the error message you're seeing.

As far as I can tell, all the other calls to endswith() in ansible/lib/ansible/plugins/terminal/dellos6.py use the b prefix, so the missing prefix in the on_become() function looks a lot like a bug.

**Comment by jsteel44** [comment]
@rolfhh thanks, just adding the "b" has fixed it (not needing the fix you mentioned for your issue). Many thanks.

**Comment by rolfhh** [comment]
@ryanmerolle Could you check if [my pull request](https://github.com/ansible/ansible/pull/59696) in the Ansible repo fixes this issue? If that is the case then it should probably also fix Ansible issue #55833.

**Comment by Dhivyap** [comment]
Fixed in PR-https://github.com/ansible/ansible/pull/63272

**Comment by Reverendheat** [comment]
This appears to still be an issue? I have made the changes @rolfhh suggested but am still having the same issues @ryanmerolle posted in the OP. 

```
ansible 2.9.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/me/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
```

```
pcName:/home/me/netBackupPlaybooks$ cat DellPB.yaml 
-
  name: Show ver
  hosts: Dell
  connection: network_cli
  gather_facts: yes
  tasks:
  -
    name: "Get Dell EMC OS6 Show Run"
    dellos6_command:
     commands: ['show ver']
   register: show_ver
  -
    name: "Backup config file locally"
    dellos6_config:
      backup: yes
      backup_options:
        dir_path: "/backup/location"
        filename: "{{ inventory_hostname }}"

```



```
<10.139.2.22> EXEC /bin/sh -c 'rm -f -r /home/me/.ansible/tmp/ansible-local-2854o4oal9vq/ansible-tmp-1582253578.8022168-188217938534126/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_dellos6_config_payload_e62Nns/ansible_dellos6_config_payload.zip/ansible/module_utils/network/dellos6/dellos6.py", line 86, in get_config
    return _DEVICE_CONFIGS[cmd]
fatal: [SWITCH2]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "after": null,
            "auth_pass": null,
            "authorize": null,
            "backup": true,
            "backup_options": null,
            "before": null,
            "config": null,
            "host": null,
            "lines": null,
            "match": "line",
            "parents": null,
            "password": null,
            "port": null,
            "provider": null,
            "replace": "line",
            "save": false,
            "src": null,
            "ssh_keyfile": null,
            "timeout": null,
            "update": "merge",
            "username": null
        }
    },
    "msg": "unable to retrieve current config",
    "stderr": "command timeout triggered, timeout value is 30 secs.\nSee the timeout setting options in the Network Debug and Troubleshooting Guide.",
    "stderr_lines": [
        "command timeout triggered, timeout value is 30 secs.",
        "See the timeout setting options in the Network Debug and Troubleshooting Guide."
    ]
}
```

Any help would be greatly appreciated..
